name: image-build

on:
  release:
    types: [published]

# Jobs
jobs:
  # Build and push magtape-init container image
  build-magtape-init-image:
    name: Push magtape-init image to DockerHub using release tag
    runs-on: ubuntu-latest

    steps:

      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Prepare
        id: prep
        #assumed that GITHUB_REF variable always is created by actions
        run: |
          echo ::set-output name=version::${GITHUB_REF#refs/tags/}
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push release tag to Docker Hub
        #if: github.repository == 'tmobile/magtape'
        timeout-minutes: 10
        uses: docker/build-push-action@v2
        with:
          context: ./app/magtape-init/
          file: ./app/magtape-init/Dockerfile
          push: true
          # tag_with_ref: true  ## this option requires a bunch of logic to implement in v2 of the action
          # this is tagging with the version number
          # tags: tmobile/magtape-init:${{ steps.prep.outputs.version }}
          tags: ilrudie/magtape-init:${{ steps.prep.outputs.version }}
 
      - name: Push magtape-init image to DockerHub using latest tag
        #if: github.repository == 'tmobile/magtape'
        timeout-minutes: 10
        uses: docker/build-push-action@v2
        with:
          context: ./app/magtape-init/
          file: ./app/magtape-init/Dockerfile
          push: true
          # tags: tmobile/magtape:latest
          tags: ilrudie/magtape-init:latest

  # Build and push magtape container image
  build-magtape-image:
    name: Push magtape image to DockerHub using release tag
    runs-on: ubuntu-latest

    steps:

      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Prepare
        id: prep
        #assumed that GITHUB_REF variable always is created by actions
        run: |
          echo ::set-output name=version::${GITHUB_REF#refs/tags/}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push release tag to Docker Hub
        #if: github.repository == 'tmobile/magtape'
        timeout-minutes: 10
        uses: docker/build-push-action@v2
        with:
          context: ./app/magtape/
          file: ./app/magtape/Dockerfile
          push: true
          # tag_with_ref: true  ## this option requires a bunch of logic to implement in v2 of the action
          # this is tagging with the version number
          # tags: tmobile/magtape-init:${{ steps.prep.outputs.version }}
          tags: ilrudie/magtape:${{ steps.prep.outputs.version }}

      - name: Push magtape image to DockerHub using latest tag
        #if: github.repository == 'tmobile/magtape'
        timeout-minutes: 10
        uses: docker/build-push-action@v2
        with:
          context: ./app/magtape/
          file: ./app/magtape/Dockerfile
          push: true
          # tags: tmobile/magtape:latest
          tags: ilrudie/magtape:latest
