name: image-build

on:
  release:
    # Dynamic version tag is set based on the assumption this ci task only runs on release
    types: [published]

# Jobs
jobs:
  # Build and push magtape-init container image
  build-magtape-init-image:
    name: Build and push magtape-init images to DockerHub
    runs-on: ubuntu-latest

    steps:

      - name: Check out the repo
        uses: actions/checkout@v2

      # Prepare is used to to collect information needed later in the action and expose it so it can be reference
      - name: Prepare
        id: prep
        # GITHUB_REF variable must exist in action; this may rely on {{ on: release: types: [published] }} gating the action
        run: |
          echo ::set-output name=version::${GITHUB_REF#refs/tags/}
          
      # Part of docker/build-push-action@v2; setting up the build system is it's own step
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      # Part of docker/build-push-action@v2; login to dockerhub is broken out into it's own step
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push magtape-init image to DockerHub using release tag
        #if: github.repository == 'tmobile/magtape'
        timeout-minutes: 10
        uses: docker/build-push-action@v2
        with:
          context: ./app/magtape-init/
          # file: should be specified relative to the repo root rather than relative to the context
          file: ./app/magtape-init/Dockerfile
          # push is no longer defaulted to true under v2; to push you must specify you want to push
          push: true
          # Uses the version output exposed by the Prepare step to set the tag under v2
          #######
          # TODO: can both tags be applied in one step in comma seperated format? v2 doc suggests this works
          # TODO: tags: ilrudie/magtape-init:${{ steps.prep.outputs.version }},ilrudie/magtape-init:latest
          #######
          # tags: tmobile/magtape-init:${{ steps.prep.outputs.version }}
          tags: ilrudie/magtape-init:${{ steps.prep.outputs.version }},ilrudie/magtape-init:latest
 
      # - name: Push magtape-init image to DockerHub using latest tag
      #   #if: github.repository == 'tmobile/magtape'
      #   timeout-minutes: 10
      #   uses: docker/build-push-action@v2
      #   with:
      #     context: ./app/magtape-init/
      #     # file: should be specified relative to the repo root rather than relative to the context
      #     file: ./app/magtape-init/Dockerfile
      #     # push is no longer defaulted to true under v2; to push you must specify you want to push
      #     push: true
      #     # overwrites the image associated with the latest tag in the repo to this new build
      #     # tags: tmobile/magtape-init:latest
      #     tags: ilrudie/magtape-init:latest

  # Build and push magtape container image
  build-magtape-image:
    name: Push magtape images to DockerHub
    runs-on: ubuntu-latest

    steps:

      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Prepare
        id: prep
        # GITHUB_REF variable must exist in action; this may rely on {{ on: release: types: [published] }} gating the action
        run: |
          echo ::set-output name=version::${GITHUB_REF#refs/tags/}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push magtape image to DockerHub using release tag
        #if: github.repository == 'tmobile/magtape'
        timeout-minutes: 10
        uses: docker/build-push-action@v2
        with:
          context: ./app/magtape/
          file: ./app/magtape/Dockerfile
          push: true
          # tags: tmobile/magtape:${{ steps.prep.outputs.version }}
          tags: ilrudie/magtape:${{ steps.prep.outputs.version }}

      - name: Push magtape image to DockerHub using latest tag
        #if: github.repository == 'tmobile/magtape'
        timeout-minutes: 10
        uses: docker/build-push-action@v2
        with:
          context: ./app/magtape/
          file: ./app/magtape/Dockerfile
          push: true
          # tags: tmobile/magtape:latest
          tags: ilrudie/magtape:latest
